name: Deploy Frontend to S3+CloudFront

on:
  push:
    branches: [ main ]

jobs:
  deploy-fe:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - run: npm ci && npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          # 二选一：推荐 OIDC 角色；或改用 AK/SK（不推荐）
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Upload immutable assets
        run: |
          aws s3 sync dist s3://${{ secrets.S3_BUCKET }}/ \
            --exclude "index.html" \
            --cache-control "public, max-age=31536000, immutable"

      - name: Upload index.html (no-cache)
        run: |
          aws s3 cp dist/index.html s3://${{ secrets.S3_BUCKET }}/index.html \
            --cache-control "no-store, max-age=0"

      - name: Invalidate index.html
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CF_DIST_ID }} \
            --paths "/index.html"
